### ISSUE TITLE
Invalid messages crash the server

### ISSUE THREAD

**Issue by runningman84** [SimpleFinance/sensu-transport-snssqs#9]
Hmm it looks like there is a new problem:

```
{"timestamp":"2016-08-09T15:43:47.093831+0000","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2016-08-09T15:43:47.093895+0000","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2016-08-09T15:43:47.093958+0000","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2016-08-09T15:43:47.094004+0000","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2016-08-09T15:43:47.094336+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2016-08-09T15:43:47.411047+0000","level":"info","message":"subscribing to type=direct, pipe=keepalives, funnel=keepalives"}
{"timestamp":"2016-08-09T15:43:47.416429+0000","level":"info","message":"subscribing to type=direct, pipe=results, funnel=results"}
{"timestamp":"2016-08-09T15:43:49.418818+0000","level":"info","message":"i am now the leader"}
{"timestamp":"2016-08-09T15:44:19.419994+0000","level":"info","message":"determining stale clients"}
{"timestamp":"2016-08-09T15:44:19.420211+0000","level":"info","message":"determining stale check results"}
{"timestamp":"2016-08-09T15:44:25.673586+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.4/lib/sensu/transport/snssqs.rb:101:in `block (3 levels) in subscribe': undefined method `string_value' for nil:NilClass (NoMethodError)
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.4/lib/sensu/transport/snssqs.rb:59:in `statsd_time'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.4/lib/sensu/transport/snssqs.rb:100:in `block (2 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:138:in `block in each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:231:in `block in spawn_workers'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.6/lib/sensu/server/process.rb:31:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.6/exe/sensu-server:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-server:22:in `load'
    from /opt/sensu/bin/sensu-server:22:in `<main>'
```

This is my config:

```
{
  "snssqs": {
    "max_number_of_messages": 10,
    "wait_time_seconds": 3,
    "region": "eu-central-1",
    "consuming_sqs_queue_url": "https://sqs.eu-central-1.amazonaws.com/12345/dev-sensu-server",
    "publishing_sns_topic_arn": "arn:aws:sns:eu-central-1:12345:dev-sensu-client"
  }
}
```

@tomwans and @cwjohnston can you take a look please?

**Comment by runningman84** [comment]
The problem is that my queue contains some invalid messages which crashes the server. These non sensu messages should be ignored. 

I create the whole stack using cloudformation. Initially the sns does not deliver raw messages. I change this settings after the stack has been created. Right now cloud formation does not allow to create raw delivery transports.

**Comment by tomwans** [comment]
I'd rather crash for now while parsing invalid messages vs. ignoring them. I would be more open to a patch that contains support for "not-raw" SQS queues, which could be optionally set. I'm going to close this out for that reason.

re: CloudFormation + raw message delivery, we use CloudFormation to set up our infrastructure as well. We manually set up the destination SQS queue and simply reference it within the CloudFormation template. Hopefully that helps.

**Comment by runningman84** [comment]
But there are also some confirmation messages in the queue if you subscribe them... Do you really want to crash every time? I think ignoring them and putting them in the dead letter queue would make more sense.

**Comment by tomwans** [comment]
Unless the default Sensu RabbitMQ transport silently ignores messages; I don't think we should either.

What "confirmation messages" are in the queue? We have no trouble ensuring that only valid sensu messages flow through the SQS queue, even while using CloudFormation.

**Comment by runningman84** [comment]
@portertech how does sensu handle invalid messages from rabbitmq or redis?

Sometimes I saw messages like sns topic subscription confirmations. 

How could we support non raw messages? Where would you recommend to convert them?

**Comment by runningman84** [comment]
Even from a security standpoint I do not want a single hacked client to be able to crash our central monitoring.

**Comment by nevins-b** [comment]
For anyone else who runs into this issue; add "keepalives": false to the client configuration seems to fix this.

**Comment by runningman84** [comment]
@nevins-b I do not think that disabling keepalives is the final solution here.

My pull request works fine in production and I see no reason why @tomwans does not want to make this transport more bullet proof.

**Comment by nevins-b** [comment]
@runningman84 I agree it's probably not a final solution but in my case that change made it so that the sensu-server didn't crash immediately. 

I think your fix is halfway there, I think any message which is not processed should be at least logged instead of silently ignored.

**Comment by runningman84** [comment]
I could still see these messages in the dead letter queue. But you are right a sensu error message would make sense. I am afraid that using redis and rabbitmq transports invalid messages could also crash the server.
